# Generated by Django 4.1.7 on 2023-04-02 16:40

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_remove_profile_avatar_profileavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=myauth.models.profile_avatars_directory_path),
        ),
        migrations.DeleteModel(
            name='ProfileAvatar',
        ),
    ]
